name: test
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
         PR_URL=$(gh pr create --head "test" --base "main" --title "testPR" --body "" -R ubw81496/test-environment)

         gh pr merge --auto -m $PR_URL
