name: test
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
         gh pr create --head "test" --base "main" --title "testPR" --body ""

         gh pr merge --auto -m https://github.com/ubw81496/test-environment/pull/3
