name: test
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
         gh pr review https://github.com/ubw81496/test-environment/pull/7 --approve
